// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2U6hYmUmAb7gHcTq2VmboG3rUURlvCL0',
    appId: '1:922229473379:web:5f2f00fb66908d4dcaf856',
    messagingSenderId: '922229473379',
    projectId: 'flooddetectioniot',
    authDomain: 'flooddetectioniot.firebaseapp.com',
    databaseURL: 'https://flooddetectioniot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flooddetectioniot.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiHxlZ0oeJjB0F0tKNrnDJqoQQE5eQdb8',
    appId: '1:922229473379:android:6e644b3d99e0af01caf856',
    messagingSenderId: '922229473379',
    projectId: 'flooddetectioniot',
    databaseURL: 'https://flooddetectioniot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flooddetectioniot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-82JXLew6VtzZLToIhVAoWNXV4uti-Lw',
    appId: '1:922229473379:ios:aa8b3a5f40d9a13ecaf856',
    messagingSenderId: '922229473379',
    projectId: 'flooddetectioniot',
    databaseURL: 'https://flooddetectioniot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flooddetectioniot.appspot.com',
    iosBundleId: 'com.example.floodDetectionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-82JXLew6VtzZLToIhVAoWNXV4uti-Lw',
    appId: '1:922229473379:ios:97fcf431c9868dcdcaf856',
    messagingSenderId: '922229473379',
    projectId: 'flooddetectioniot',
    databaseURL: 'https://flooddetectioniot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flooddetectioniot.appspot.com',
    iosBundleId: 'com.example.floodDetectionApp.RunnerTests',
  );
}
